//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auto_Kindle.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\gmanrodt\\Desktop\\mobi\\C#\\app\\mobi2mobi.exe")]
        public string mobi2mobiAppPath {
            get {
                return ((string)(this["mobi2mobiAppPath"]));
            }
            set {
                this["mobi2mobiAppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\gmanrodt\\Desktop\\mobi\\C#\\app\\clit.exe")]
        public string clitAppPath {
            get {
                return ((string)(this["clitAppPath"]));
            }
            set {
                this["clitAppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\gmanrodt\\Desktop\\mobi\\C#\\appabcpalm.exe")]
        public string pdbAppPath {
            get {
                return ((string)(this["pdbAppPath"]));
            }
            set {
                this["pdbAppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\gmanrodt\\Desktop\\mobi\\C#\\app\\chmdecoder.exe")]
        public string chmAppPath {
            get {
                return ((string)(this["chmAppPath"]));
            }
            set {
                this["chmAppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\gmanrodt\\Desktop\\mobi\\C#\\app\\pdftohtml.exe")]
        public string pdfAppPath {
            get {
                return ((string)(this["pdfAppPath"]));
            }
            set {
                this["pdfAppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string mobi2mobiAppArgs {
            get {
                return ((string)(this["mobi2mobiAppArgs"]));
            }
            set {
                this["mobi2mobiAppArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-d")]
        public string clitAppArgs {
            get {
                return ((string)(this["clitAppArgs"]));
            }
            set {
                this["clitAppArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pdbAppArgs {
            get {
                return ((string)(this["pdbAppArgs"]));
            }
            set {
                this["pdbAppArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-menu")]
        public string chmAppArgs {
            get {
                return ((string)(this["chmAppArgs"]));
            }
            set {
                this["chmAppArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-noframes -c")]
        public string pdfAppArgs {
            get {
                return ((string)(this["pdfAppArgs"]));
            }
            set {
                this["pdfAppArgs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\kindle\\temp")]
        public string TempPath {
            get {
                return ((string)(this["TempPath"]));
            }
            set {
                this["TempPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\kindle\\Fiction")]
        public string EBookPath {
            get {
                return ((string)(this["EBookPath"]));
            }
            set {
                this["EBookPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\gmanrodt\\Desktop\\mobi\\C#\\app\\mobigen.exe")]
        public string MobigenPath {
            get {
                return ((string)(this["MobigenPath"]));
            }
            set {
                this["MobigenPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\kindle\\converted")]
        public string DefaultOutPath {
            get {
                return ((string)(this["DefaultOutPath"]));
            }
            set {
                this["DefaultOutPath"] = value;
            }
        }
    }
}
